using Mate.Entities.Concrete;
using Mate.Entities.EntityConfig.Abstract;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Mate.Entities.EntityConfig.Concrete
{
	public class ProductConfig : BaseConfig<Product>
	{
		public override void Configure(EntityTypeBuilder<Product> builder)
		{
			base.Configure(builder);

			builder.Property(x => x.ProductName).IsRequired().HasMaxLength(50);
			builder.Property(x => x.Description).HasMaxLength(200);

			builder.Property(x => x.IsAdult).IsRequired();
			builder.Property(x => x.Amount).IsRequired();

			builder.Property(x => x.UnitPriceForSale).HasMaxLength(100000);
			builder.Property(x => x.UnitPriceForRent).HasMaxLength(100000);
			builder.Property(x => x.IsSale).IsRequired();
			builder.Property(x => x.Gender).HasMaxLength(20);


			builder.HasOne(p => p.ProductCategories).WithMany(p => p.Products).HasForeignKey(p => p.ProductCategoryId).IsRequired();
			builder.HasOne(p => p.ProductRegions).WithMany(p => p.Products).HasForeignKey(p => p.ProductRegionId);
			builder.HasOne(p => p.ProductSubRegions).WithMany(p => p.Products).HasForeignKey(p => p.ProductSubRegionId);

			//UnitPriceForsale = 1500,
			//ÇOCUK
			//1.HALK OYUNLARI ÇOCUK

			builder.HasData(new Product() { ProductName = "ADIYAMAN", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "ADIYAMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNADIYAMANÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ANKARA", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", ProductSubRegionId = "ANKARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNANKARAÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ARTVİN", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "ARTVİN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNARTVİNÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ARTVİN İŞLİ", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "ARTVİN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNARTVİN-İŞLİÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "BİLECİK", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "BİLECİK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBİLECİKÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "BİTLİS E", Amount = 10, Gender = false, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBİTLİS-EÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "BİTLİS K", Amount = 10, Gender = true, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBİTLİS-KÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "BOLU İŞLİ", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "BOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBOLU-İŞLİÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "BOLU SADE", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "BOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBOLU-SADEÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "DİYARBAKIR", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "DİYARBAKIR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNDİYARBAKIRÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ELAZIĞ", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "ELAZIĞ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNELAZIĞÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GAZİANTEP K", Amount = 10, Gender = true, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "GAZİANTEP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNGAZİANTEP-KÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GAZİANTEP E", Amount = 10, Gender = false, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "GAZİANTEP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNGAZİANTEP-EÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "HALAY KIRMIZI", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductSubRegionId = "HALAY", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNHALAY-KIRMIZIÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "HALAY SİYAH", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductSubRegionId = "HALAY", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNHALAY-SİYAHÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KARADENİZ", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNKARADENİZÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KAFKAS KIRMIZI", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNKAFKAS-KIRMIZIÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KAFKAS MOR", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNKAFKAS-MORÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "SİLİFKE", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "SİLİFKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNSİLİFKEÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TEKE E", Amount = 10, Gender = false, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "TEKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTEKE-EÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TEKE YEŞİL", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "TEKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTEKE-YEŞİLÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TEKE PEMBE", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "TEKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTEKE-PEMBEÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRAKYA", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTRAKYAÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ÜSKÜP", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", ProductSubRegionId = "ÜSKÜP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNÜSKÜPÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRAKYA PEMBE", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTRAKYA-PEMBEÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRAKYA BEYAZ", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTRAKYA-BEYAZÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "VAN", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "VAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNVANÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ZEYBEK BORDO", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNZEYBEK-BORDOÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ZEYBEK E", Amount = 10, Gender = false, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNZEYBEK-EÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ZEYBEK İŞLİ", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNZEYBEK-İŞLİÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ZEYBEK MOR", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNZEYBEK-MORÇOCUKKİRALIK.jpg" });



			//3. STİLİZE DANS ÇOCUK

			builder.HasData(new Product() { ProductName = "ÇAÇA", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEÇAÇAÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "FRAK", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEFRAKÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GREASE", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEGREASEÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "HİNT", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEHİNTÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "İSPANYOL", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEİSPANYOLÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ROMAN FUŞYA", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEROMANFUŞYAÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ROMAN KIRMIZI", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEROMANKIRMIZIÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ROMAN KIR (1)", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEROMANKIR1ÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ROMAN MOR", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEROMANMORÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "SALSA", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESALSAÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "SALSA E", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESALSAEÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "STİLİZE KIRMIZI", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZEKIRMIZIÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "STİLİZE MOR", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZEMORÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "STİLİZE PEMBE", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZEPEMBEÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "STİLİZE SARI", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZESARIÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ÇİFTETELLİ PEMBE", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEÇİFTETELLİPEMBEÇOCUKKİRALIK.jpg" });




			//ÇOCUK 4. ROND TÖREN
			// Kiralık Yıl Sonu Gösteri Kıyafetleri - Asker Kıyafeti Kiralama-Çanakkale Askeri Kıyafeti
			//KİRALIK ÇOCUK GÖSTERİ ve TÖREN KOSTÜMLERİ




			builder.HasData(new Product() { ProductName = "ARI", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDARIÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ASKER", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDASKERÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ÇAÇA", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEÇAÇAÇOCUKKİRALIK.jpg" });//STİLİZEDEN ÇEKİLDİ
			builder.HasData(new Product() { ProductName = "ÇİÇEK", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDÇİÇEKÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "FARE", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDFAREÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "HACİVAT KARAGÖZ", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDHACİVATKARAGÖZÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "İSPANYOL", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEİSPANYOLÇOCUKKİRALIK.jpg" });//STİLİZEDEN ÇEKTİM
			builder.HasData(new Product() { ProductName = "KATİBİM", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDKATİBİMÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KIRMIZI BAŞLIKLI KIZ", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDKIRMIZIBAŞLIKLIKIZÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "MEHTER", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDMEHTERÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "MEZUNİYET", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDMEZUNİYETÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "NASREDDİN HOCA", Amount = 10, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDNASREDDİNHOCAÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "NOEL BABA", Amount = 10, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDNOELBABAÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ÖRDEK", Amount = 10, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDÖRDEKÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "PADİŞAH", Amount = 10, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDPADİŞAHÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "PALYAÇO", Amount = 10, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDPALYAÇOÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "PAMUK PRENSES", Amount = 10, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDPAMUKPRENSESÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "SALSA K", Gender = true, Amount = 10, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDSALSAKÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "SEMAZEN", Amount = 10, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDSEMAZENÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ŞİRİNLER", Amount = 10, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDŞİRİNLERÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TAVŞAN", Amount = 10, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDTAVŞANÇOCUKKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "STİLİZE KIRMIZI", Amount = 10, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZEKIRMIZIÇOCUKKİRALIK.jpg" });//STİLİZEDEN ÇEKTİM
			builder.HasData(new Product() { ProductName = "STİLİZE SARI", Amount = 10, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZESARIÇOCUKKİRALIK.jpg" });//STİLİZEDEN ÇEKTİM
			builder.HasData(new Product() { ProductName = "YENİÇERİ", Amount = 10, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDYENİÇERİÇOCUKKİRALIK.jpg" });




			////YETİŞKİN
			////1.HALK OYUNLARI YETİŞKİN
			////YETİSKİNYÖRESELKIYAFETLERİ
			builder.HasData(new Product() { ProductName = "ADIYAMAN E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "ADIYAMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADIYAMAN-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ADIYAMAN K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "ADIYAMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADIYAMAN-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ANKARA E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", ProductSubRegionId = "ANKARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ANKARA-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ARTVİN E2", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "ARTVİN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-E2-YETİŞKİNKİRALIK.jpG" });
			builder.HasData(new Product() { ProductName = "ARTVİN K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "ARTVİN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "BİLECİK K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "BİLECİK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİLECİK-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "BİTLİS BEYAZ E", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİSBEYAZ-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "BİTLİS K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİS-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "BİTLİS MAVİ", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİSMAVİ-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "BOLU K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "BOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BOLU-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "BURDUR E2", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "BURDUR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURDUR-E2-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "BURDUR K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "BURDUR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURDUR-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "DİYARBAKIR E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "DİYARBAKIR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DİYARBAKIR-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "DİYARBAKIR K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "DİYARBAKIR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DİYARBAKIR-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GAZİANTEP E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "GAZİANTEP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GAZİANTEP K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "GAZİANTEP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GİRESUN E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "GİRESUN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GİRESUN-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GİRESUN K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "GİRESUN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GİRESUN-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "HAKKARİ K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "HAKKARİ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-HAKKARİ-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KAFKAS E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KAFKAS K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "SİLİFKE E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "SİLİFKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "SİLİFKE K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "SİLİFKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRAKYA KIRMIZI KADİFE", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAKIRMIZIKADİFE-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRAKYA KREM", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAKREM-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRAKYA MAVİ", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAMAVİ-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRAKYA MOR MONORAY", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAMORMONORAY-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRAKYA PEMBE K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAPEMBE-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRABZON E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRABZON K İŞLİK", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONİŞLİK-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRABZON MOR İŞLİK", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONMORİŞLİK-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRABZON MOR YELEK", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONMORYELEK-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "TRABZON PEMBE YELEK", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONPEMBEYELEK-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ÜSKÜP E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", ProductSubRegionId = "ÜSKÜP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜP-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ÜSKÜP K BORDO", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", ProductSubRegionId = "ÜSKÜP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPBORDO-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "VAN BEYAZ", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "VAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VANBEYAZ-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "VAN K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "VAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VAN-K-YETİŞKİNKİRALIK.jpg" });

			builder.HasData(new Product() { ProductName = "ZEYBEK AÇIK E", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKAÇIK-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ZEYBEK AĞIR E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKAĞIR-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ZEYBEK BORDO", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKBORDO-YETİŞKİNKİRALIK.jpg" });// BURALARDA KAYDIRMA YAPTIMMM!!!!!		
			builder.HasData(new Product() { ProductName = "ZEYBEK EŞKİYA E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKEŞKİYA-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ZEYBEK KOYU E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKKOYU-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ZEYBEK MOR", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKMOR-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ZEYBEK PEMBE", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKPEMBE-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ZEYBEK MUĞLA", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKMUĞLA-YETİŞKİNKİRALIK.jpg" });
			//2.BİNDALLI VE KINA YETİŞKİN
			builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN BORDO", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANBORDO-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN KIRMIZI", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANKIRMIZI-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN KIRMIZI-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANKIRMIZI-N2-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN KIRMIZI-N3", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANKIRMIZI-N3-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN MOR", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANMOR-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN MÜRDÜM", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANMÜRDÜM-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN PEMBE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANPEMBE-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN YEŞİL", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANYEŞİL-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KINA KIYAFETİ BORDO", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİBORDO-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KINA KIYAFETİ GRİ-SİYAH", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİGRİSİYAH-YETİŞKİNKİRALIK.jpg" }); ;
			builder.HasData(new Product() { ProductName = "KINA KIYAFETİ KIRMIZI", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİKIRMIZI-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KINA KIYAFETİ KIRMIZI-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİKIRMIZI-N2-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KINA KIYAFETİ LACİVERT", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİLACİVERT-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KINA KIYAFETİ LACİVERT-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİLACİVERT-N2-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KINA KIYAFETİ LACİVERT-N3", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİLACİVERT-N3-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KINA KIYAFETİ PEMBE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİPEMBE-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KINA KIYAFETİ PEMBE-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİPEMBE-N2-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KINA KIYAFETİ ÜSKÜP-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİÜSKÜP-N2-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "KINA KIYAFETİ YEŞİL", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİYEŞİL-YETİŞKİNKİRALIK.jpg" });

			//3. STİLİZE DANS
			//Kostüm Kiralama - Stilize Dans,Salsa ve Roman Kostümleri
			//YETİŞKİN STİLİZE DANS ve ROMAN KOSTÜMLERİ
			builder.HasData(new Product() { ProductName = "AŞUK MAŞUK", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-AŞUKMAŞUK-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ÇİFTETELLİ BEYAZ", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ÇİFTETELLİ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ÇİFTETELLİBEYAZ-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "LİRİK", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-LİRİK-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ROMAN FUŞYA", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANFUŞYA-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ROMAN KIRMIZI", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANKIRMIZI-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ROMAN PEMBE", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANPEMBE-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ROMAN RENKLİ ETEK", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANRENKLİETEK-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ROMAN TURUNCU", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANTURUNCU-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "ROMAN YEŞİL", Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANYEŞİL-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "STİLİZE KIRMIZI E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-STİLİZEKIRMIZI-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "STİLİZE KIRMIZI K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-STİLİZEKIRMIZI-K-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "STİLİZE MAVİ E", Gender = false, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-STİLİZEMAVİ-E-YETİŞKİNKİRALIK.jpg" });
			builder.HasData(new Product() { ProductName = "STİLİZE MAVİ K", Gender = true, Amount = 10, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-STİLİZEMAVİ-K-YETİŞKİNKİRALIK.jpg" });

			// c:de kii
		}
	}
}
