using Mate.Entities.Concrete;
using Mate.Entities.EntityConfig.Abstract;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Mate.Entities.EntityConfig.Concrete
{
    public class ProductConfig : BaseConfig<Product>
    {
        public override void Configure(EntityTypeBuilder<Product> builder)
        {
            base.Configure(builder);

            builder.Property(x => x.ProductName).IsRequired().HasMaxLength(50);
            builder.Property(x => x.Description).HasMaxLength(200);

            builder.Property(x => x.IsAdult).IsRequired();
            //builder.Property(x => x.Amount).IsRequired();

            builder.Property(x => x.UnitPriceForSale).HasMaxLength(100000);
            builder.Property(x => x.UnitPriceForRent).HasMaxLength(100000);
            builder.Property(x => x.IsSale).IsRequired();
            builder.Property(x => x.Gender).HasMaxLength(20);
            //builder.HasIndex(x => x.PhotoPath).IsUnique();

            builder.HasOne(p => p.ProductCategories).WithMany(p => p.Products).HasForeignKey(p => p.ProductCategoryId).IsRequired();
            builder.HasOne(p => p.ProductRegions).WithMany(p => p.Products).HasForeignKey(p => p.ProductRegionId);
            builder.HasOne(p => p.ProductSubRegions).WithMany(p => p.Products).HasForeignKey(p => p.ProductSubRegionId);

            //UnitPriceForsale = 1500,
            //ÇOCUK
            //1.HALK OYUNLARI ÇOCUK

            builder.HasData(new Product() { Id = "1c370cf8-9f6e-42fa-b7f0-1dce0caa5364", ProductName = "ADIYAMAN", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "ADIYAMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNADIYAMANÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "8f39d68e-fbf3-4323-8c5a-d8b55cffef2a", ProductName = "ANKARA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", ProductSubRegionId = "ANKARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNANKARAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "b5b67003-636d-425d-9784-45d374db713c", ProductName = "ARTVİN", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "ARTVİN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNARTVİNÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "f4ec3d57-0958-4cd2-8d1f-e3038eb75ae2", ProductName = "ARTVİN İŞLİ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "ARTVİN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNARTVİN-İŞLİÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "6fa2bd76-8f79-42d6-ae51-2f7a95535f7d", ProductName = "BİLECİK", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "BİLECİK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBİLECİKÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "43b8b3e0-4ac0-4b56-b0b9-e49cd0d9edd1", ProductName = "BİTLİS E", Gender = false, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBİTLİS-EÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "8601b2c5-4e87-49e4-9099-8c21a9ca00b4", ProductName = "BİTLİS K", Gender = true, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBİTLİS-KÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "f39485eb-f82b-495c-8b60-7dada21ee477", ProductName = "BOLU İŞLİ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "BOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBOLU-İŞLİÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "50680664-523a-475b-869f-0aa5e0cd88b4", ProductName = "BOLU SADE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "BOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBOLU-SADEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "9445ce49-5efd-41b8-bdab-b8d7f350b5e2", ProductName = "DİYARBAKIR", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "DİYARBAKIR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNDİYARBAKIRÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "0c59ca0d-60e5-4686-80be-18ab36b53468", ProductName = "ELAZIĞ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "ELAZIĞ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNELAZIĞÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "bfdaeb2e-2ddb-4fc7-b971-58d61cbf4ba3", ProductName = "GAZİANTEP K", Gender = true, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "GAZİANTEP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNGAZİANTEP-KÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "ea3367e6-6d1c-4e58-883a-b18d66f30f8b", ProductName = "GAZİANTEP E", Gender = false, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "GAZİANTEP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNGAZİANTEP-EÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "dd438551-3d93-45bc-982d-7c338b69983b", ProductName = "HALAY KIRMIZI", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductSubRegionId = "HALAY", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNHALAY-KIRMIZIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "43606bc6-5874-4469-bcdf-fe1b86f66882", ProductName = "HALAY SİYAH", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductSubRegionId = "HALAY", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNHALAY-SİYAHÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "2146af26-ce2b-461b-883b-e6f4fe0c8085", ProductName = "KARADENİZ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNKARADENİZÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "6f169352-0f68-4d11-b562-f693a0158100", ProductName = "KAFKAS KIRMIZI", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNKAFKAS-KIRMIZIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "ad918937-0645-4b89-86d5-0672662fd46e", ProductName = "KAFKAS MOR", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNKAFKAS-MORÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "52a0bd63-231d-4620-9e7a-10b6d4fb8b65", ProductName = "SİLİFKE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "SİLİFKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNSİLİFKEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "a9f573a8-2c98-4861-9a93-b90d3e8bc6fa", ProductName = "TEKE E", Gender = false, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "TEKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTEKE-EÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "23672a63-2fd2-4e6a-905b-340ae4456b83", ProductName = "TEKE YEŞİL", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "TEKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTEKE-YEŞİLÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "7d543840-b11e-4380-a147-7dab483cf5ce", ProductName = "TEKE PEMBE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "TEKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTEKE-PEMBEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "bd0cb50a-e769-48ed-8473-b25faa687e15", ProductName = "TRAKYA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTRAKYAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "f20906f6-cdbb-4f93-9ad0-87e63f0782ff", ProductName = "ÜSKÜP", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", ProductSubRegionId = "ÜSKÜP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNÜSKÜPÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "d501bc94-2256-4ce7-b0bf-be4357ada814", ProductName = "TRAKYA PEMBE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTRAKYA-PEMBEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "cb1e122c-1eff-4130-a8e5-cef23cfa8ac1", ProductName = "TRAKYA BEYAZ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTRAKYA-BEYAZÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "c5dbd9c2-70b4-451d-99cb-5130ab97ed0d", ProductName = "VAN", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "VAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNVANÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "4aa47021-28ed-4c36-81c3-6e2734d3873b", ProductName = "ZEYBEK BORDO", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNZEYBEK-BORDOÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "78157107-23fa-4638-bd17-38187695312c", ProductName = "ZEYBEK E", Gender = false, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNZEYBEK-EÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "a278895c-19b5-45c6-92f9-48c5f2724e8a", ProductName = "ZEYBEK İŞLİ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNZEYBEK-İŞLİÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "7e6e25fd-0c9c-44ea-b2cf-61f70a9fd3ce", ProductName = "ZEYBEK MOR", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNZEYBEK-MORÇOCUKKİRALIK.jpg" });



            //3. STİLİZE DANS ÇOCUK

            builder.HasData(new Product() { Id = "2a29a1d6-b3e1-4724-ba5e-8cbd92a1c34f", ProductName = "ÇAÇA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEÇAÇAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "5a382843-9817-449b-b9d8-4e48d90aef5e", ProductName = "FRAK", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEFRAKÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "618fdb18-11c3-4166-9bb1-79298a32a7a4", ProductName = "GREASE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEGREASEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "2e5e4216-4af5-4fb6-9c65-8989715e5a40", ProductName = "HİNT", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEHİNTÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "77035e08-21a9-4149-8d7c-d4266f88ad03", ProductName = "İSPANYOL", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEİSPANYOLÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "5e029621-e6b2-476c-9ad6-ce8d6ecc24f3", ProductName = "ROMAN FUŞYA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEROMANFUŞYAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "98e89d8e-aa22-4ba3-8e1d-0ccc1e9f3747", ProductName = "ROMAN KIRMIZI", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEROMANKIRMIZIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "3f6f1dbc-9042-42c2-85ca-a117c745c5e8", ProductName = "ROMAN KIR (1)", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEROMANKIR1ÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "43ca244e-8d5a-468b-b327-ce6bdc541cf7", ProductName = "ROMAN MOR", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEROMANMORÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "9880f4c6-87bd-42a6-8c30-f00b3b4e1f8e", ProductName = "SALSA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESALSAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "aca583cc-1e5b-4db1-a9d4-6d8d53ae7e67", ProductName = "SALSA E", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESALSAEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "1bab3f06-eb4a-4e6f-8506-ce9fb7c7c56d", ProductName = "STİLİZE KIRMIZI", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZEKIRMIZIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "4a67e8f3-4dec-41ad-a5e7-18995a14535d", ProductName = "STİLİZE MOR", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZEMORÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "d6003f61-89ae-4240-b53c-542ab36728ca", ProductName = "STİLİZE PEMBE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZEPEMBEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "1a9626f8-303d-41e3-aa54-ae1a971ad179", ProductName = "STİLİZE SARI", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZESARIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "3770c1af-e181-494b-8c1a-c6f09a3b825a", ProductName = "ÇİFTETELLİ PEMBE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEÇİFTETELLİPEMBEÇOCUKKİRALIK.jpg" });




            //ÇOCUK 4. ROND TÖREN
            // Kiralık Yıl Sonu Gösteri Kıyafetleri - Asker Kıyafeti Kiralama-Çanakkale Askeri Kıyafeti
            //KİRALIK ÇOCUK GÖSTERİ ve TÖREN KOSTÜMLERİ




            builder.HasData(new Product() { Id = "a2bcb56b-1da2-43fc-b133-3b5c04603123", ProductName = "ARI", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDARIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "6bdd753a-2706-48b6-b485-23c989a5f326", ProductName = "ASKER", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDASKERÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "121345d8-2660-489c-a90d-2469b9c44222", ProductName = "ÇAÇA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDÇAÇAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "b8b726c6-227d-4267-8dba-c1bf5ec0301f", ProductName = "ÇİÇEK", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDÇİÇEKÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "6e0185cc-235f-4603-9470-5f4ca7c92514", ProductName = "FARE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDFAREÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "cd3be091-3d72-4512-ba1d-e8466285b930", ProductName = "HACİVAT KARAGÖZ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDHACİVATKARAGÖZÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "4b656abf-bdc5-4058-a12b-488d93cc1677", ProductName = "İSPANYOL", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDİSPANYOLÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "c35ccc97-39f5-4396-bbe1-2a6171f30d10", ProductName = "KATİBİM", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDKATİBİMÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "809d901e-d7de-4fec-aa95-655deb2301b6", ProductName = "KIRMIZI BAŞLIKLI KIZ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDKIRMIZIBAŞLIKLIKIZÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "111c9f5f-bd2b-4fc2-9806-5f2e74eaacfb", ProductName = "MEHTER", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDMEHTERÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "f03ff26b-30e9-4a60-b99a-780060db1e35", ProductName = "MEZUNİYET", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDMEZUNİYETÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "72d46b9b-612d-41c4-8303-8f8571771de9", ProductName = "NASREDDİN HOCA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDNASREDDİNHOCAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "229759ff-14dd-4c4e-82aa-f56a2181c0ad", ProductName = "NOEL BABA", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDNOELBABAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "41ba1e6a-1ac7-4cee-902c-6bc1bc46641e", ProductName = "ÖRDEK", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDÖRDEKÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "f4bab42f-1bb5-4ab3-9b00-22f1f33f006c", ProductName = "PADİŞAH", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDPADİŞAHÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "3e2f7a5f-b665-4b13-861e-c5a5029216a0", ProductName = "PALYAÇO", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDPALYAÇOÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "cae31f17-a52f-4ac3-97bb-6886500b19bf", ProductName = "PAMUK PRENSES", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDPAMUKPRENSESÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "ed9ab94a-9354-48de-8695-43131a67bd2c", ProductName = "SALSA K", Gender = true, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDSALSAKÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "289fa380-9e0f-4fbb-ab6f-4f462ee90f0a", ProductName = "SEMAZEN", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDSEMAZENÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "c941ed50-01c0-472d-8122-3756b9b55a29", ProductName = "ŞİRİNLER", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDŞİRİNLERÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "a34e2f74-5403-4e43-bc88-30019ebd460f", ProductName = "TAVŞAN", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDTAVŞANÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "8906cf96-12d6-4eca-8a0b-d39dd78dc597", ProductName = "STİLİZE KIRMIZI", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDSTİLİZEKIRMIZIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "b6dd4dd8-5922-46f8-9ea5-1e5a7953330f", ProductName = "STİLİZE SARI", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDSTİLİZESARIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "b2b71d89-5501-4bd6-a358-aca8ce706bdb", ProductName = "YENİÇERİ", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDYENİÇERİÇOCUKKİRALIK.jpg" });




            ////YETİŞKİN
            ////1.HALK OYUNLARI YETİŞKİN
            ////YETİSKİNYÖRESELKIYAFETLERİ
            builder.HasData(new Product() { Id = "f336bdc4-fd5f-4ffc-ba3d-0800649bb0d2", ProductName = "ADIYAMAN E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "ADIYAMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADIYAMAN-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "00e2e1d5-5577-4f8e-b13b-dde82c77b91d", ProductName = "ADIYAMAN K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "ADIYAMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADIYAMAN-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "01388782-b75d-4762-8ccf-4499568fd455", ProductName = "ANKARA E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", ProductSubRegionId = "ANKARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ANKARA-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "5b26e8ac-df32-4b9d-8992-047e22372332", ProductName = "ARTVİN E2", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "ARTVİN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-E2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "5754a3be-8508-452d-8a64-9d752bde4f70", ProductName = "ARTVİN K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "ARTVİN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "6eee1f90-a40d-4d95-9ca6-0e45689398be", ProductName = "BİLECİK K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "BİLECİK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİLECİK-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "cf03ef83-babf-4710-ab13-ace35476b474", ProductName = "BİTLİS BEYAZ E", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİSBEYAZ-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "35ecfa79-7e24-4e50-bb2f-05a1b4dc529b", ProductName = "BİTLİS K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİS-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "b5e13a1d-86f3-415c-9c2f-4343258a4b57", ProductName = "BİTLİS MAVİ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİSMAVİ-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "0f1d6d17-8b8b-489d-a0f6-7349691aadd6", ProductName = "BOLU K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "BOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BOLU-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "94430690-6bd2-4e48-b0c3-4de11c7f5d81", ProductName = "BURDUR E2", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "BURDUR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURDUR-E2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "89c5b8e4-4c60-4e08-88ad-4509be08bde4", ProductName = "BURDUR K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "BURDUR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURDUR-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "6fe7b587-9518-460f-8c8f-7aa43ad55f9c", ProductName = "DİYARBAKIR E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "DİYARBAKIR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DİYARBAKIR-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "e9ca0d20-0315-4fca-b334-e6e046cd076e", ProductName = "DİYARBAKIR K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "DİYARBAKIR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DİYARBAKIR-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "676211f2-1f90-4059-bdf8-9e26f9a637a4", ProductName = "GAZİANTEP E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "GAZİANTEP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "c24852f9-007d-455a-8cb5-0e2681c7a0a5", ProductName = "GAZİANTEP K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "GAZİANTEP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "f7062df1-beb7-4814-a074-e9da66830639", ProductName = "GİRESUN E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "GİRESUN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GİRESUN-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "43f658bf-a5f4-4537-a281-77dbb5ce1c27", ProductName = "GİRESUN K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "GİRESUN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GİRESUN-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "d99cdf9c-bda7-4807-b92e-34b3de2e6002", ProductName = "HAKKARİ K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "HAKKARİ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-HAKKARİ-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "74aa5d7a-f513-4993-b672-cdf9bb448319", ProductName = "KAFKAS E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "0e9b45b3-2915-4dcd-99fa-77ad89f182a4", ProductName = "KAFKAS K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "a08d4c19-059b-42bc-83db-26206735e40f", ProductName = "SİLİFKE E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "SİLİFKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "db604d4c-9f40-48f5-b244-9b3bdcaf71c1", ProductName = "SİLİFKE K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "SİLİFKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "7a3ccc47-8f30-4952-8909-ed3537cfe7e5", ProductName = "TRAKYA KIRMIZI KADİFE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAKIRMIZIKADİFE-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "748cbc1e-8d05-4f4f-8196-9cfb28db232c", ProductName = "TRAKYA KREM", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAKREM-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "4779905b-91b3-4878-97e0-58a010668be5", ProductName = "TRAKYA MAVİ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAMAVİ-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "ff51a10a-1e10-4f3f-9d7b-b9342fd12bdc", ProductName = "TRAKYA MOR MONORAY", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAMORMONORAY-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "226fad45-0bcb-4ee2-a4de-0deb8baf8d4c", ProductName = "TRAKYA PEMBE K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAPEMBE-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "5b36c084-dce0-4ba9-ba55-613210750e27", ProductName = "TRABZON E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "cd3167af-629a-4795-8c18-cf4f49e0a7d1", ProductName = "TRABZON K İŞLİK", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONİŞLİK-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "775cd819-72cc-4aa7-89ac-2e89dcbe5c0a", ProductName = "TRABZON MOR İŞLİK", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONMORİŞLİK-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "a07ed297-38cd-456e-834f-c31583eab987", ProductName = "TRABZON MOR YELEK", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONMORYELEK-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "523db500-84c9-42fa-bf24-f66e77e724e5", ProductName = "TRABZON PEMBE YELEK", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONPEMBEYELEK-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "69191d39-5c1b-4261-b0d7-48a7833e08bd", ProductName = "ÜSKÜP E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", ProductSubRegionId = "ÜSKÜP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜP-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "2b514c67-a65f-4c0a-86b8-5bf92a974c34", ProductName = "ÜSKÜP K BORDO", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", ProductSubRegionId = "ÜSKÜP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPBORDO-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "d7a31657-3101-42e7-8b97-aa6ff61d3e84", ProductName = "VAN BEYAZ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "VAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VANBEYAZ-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "8abdfc01-6b02-4b55-93d3-eea25b17de37", ProductName = "VAN K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "VAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VAN-K-YETİŞKİNKİRALIK.jpg" });

            builder.HasData(new Product() { Id = "4a450a7f-5ca6-42f5-9931-e130264c8e0c", ProductName = "ZEYBEK AÇIK E", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKAÇIK-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "ffcc6812-deda-4b92-b2dd-0f59e0a46c44", ProductName = "ZEYBEK AĞIR E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKAĞIR-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "9c301f9b-43b4-4015-bc1d-70ad1b2b690e", ProductName = "ZEYBEK BORDO", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKBORDO-YETİŞKİNKİRALIK.jpg" });// BURALARDA KAYDIRMA YAPTIMMM!!!!!		
            builder.HasData(new Product() { Id = "09ff2634-4a59-46ce-94c7-8428324d789f", ProductName = "ZEYBEK EŞKİYA E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKEŞKİYA-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "5eaed820-0af4-4157-8fea-1f58baa77661", ProductName = "ZEYBEK KOYU E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKKOYU-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "aee09720-0d54-473a-b585-c62d6c516e68", ProductName = "ZEYBEK MOR", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKMOR-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "4f8cc09d-7512-44d8-a98c-3004c93031f0", ProductName = "ZEYBEK PEMBE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKPEMBE-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "56072689-4550-44be-987e-b08667758de4", ProductName = "ZEYBEK MUĞLA", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKMUĞLA-YETİŞKİNKİRALIK.jpg" });
            //2.BİNDALLI VE KINA YETİŞKİN
            builder.HasData(new Product() { Id = "c8e6b9db-dbc9-4d49-a473-2c8593982b56", ProductName = "GELENEKSEL KAFTAN BORDO", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANBORDO-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "31b00595-bfeb-47b6-9af3-91d117e003d4", ProductName = "GELENEKSEL KAFTAN KIRMIZI", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANKIRMIZI-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "c99efd04-1f14-49e6-bd60-208290d057a6", ProductName = "GELENEKSEL KAFTAN KIRMIZI-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANKIRMIZI-N2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "b7f47693-ed7e-4c7c-8ef2-c4909b2d2659", ProductName = "GELENEKSEL KAFTAN KIRMIZI-N3", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANKIRMIZI-N3-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "c38c7a52-bc3b-4095-bbc3-ea23c389a9f8", ProductName = "GELENEKSEL KAFTAN MOR", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANMOR-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "5f9a2c76-50a5-4e93-95c9-158ae078c357", ProductName = "GELENEKSEL KAFTAN MÜRDÜM", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANMÜRDÜM-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "e35c267e-66ab-453d-ba33-a31c4ce7e5ed", ProductName = "GELENEKSEL KAFTAN PEMBE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANPEMBE-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "81cb9635-df03-42c8-8d68-944f99de02ca", ProductName = "GELENEKSEL KAFTAN YEŞİL", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANYEŞİL-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "6d3fcb11-b20a-47f2-aab4-bbceb420ea3d", ProductName = "KINA KIYAFETİ BORDO", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİBORDO-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "976d92d5-de98-47ea-a219-26842c7f8caf", ProductName = "KINA KIYAFETİ GRİ-SİYAH", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİGRİSİYAH-YETİŞKİNKİRALIK.jpg" }); ;
            builder.HasData(new Product() { Id = "6183a2d7-d2c5-4828-bccb-754ce1bbb002", ProductName = "KINA KIYAFETİ KIRMIZI", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİKIRMIZI-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "b7a53fcf-0ef2-4cf2-ab4a-6fdd3c2e655c", ProductName = "KINA KIYAFETİ KIRMIZI-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİKIRMIZI-N2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "41c0e64a-97f8-45fa-a2b3-399ed47cddcc", ProductName = "KINA KIYAFETİ LACİVERT", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİLACİVERT-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "f43faef4-2885-42c1-9035-ccc2667d7fca", ProductName = "KINA KIYAFETİ LACİVERT-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİLACİVERT-N2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "fb0deebe-ca58-4eb6-ac5b-67442c846405", ProductName = "KINA KIYAFETİ LACİVERT-N3", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİLACİVERT-N3-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "c474ff32-d65e-4d11-90a2-f9ad2e8ee772", ProductName = "KINA KIYAFETİ PEMBE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİPEMBE-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "c15e0f9b-39be-49ff-aff8-1800116358f7", ProductName = "KINA KIYAFETİ PEMBE-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİPEMBE-N2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "04a7d241-f761-4ead-803b-1d204df7bd53", ProductName = "KINA KIYAFETİ ÜSKÜP-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİÜSKÜP-N2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "bb1dfb9b-70aa-495e-a041-156a4fbb4fec", ProductName = "KINA KIYAFETİ YEŞİL", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİYEŞİL-YETİŞKİNKİRALIK.jpg" });

            //3. STİLİZE DANS
            //Kostüm Kiralama - Stilize Dans,Salsa ve Roman Kostümleri
            //YETİŞKİN STİLİZE DANS ve ROMAN KOSTÜMLERİ
            builder.HasData(new Product() { Id = "e0f91ecb-de8b-44fb-9a15-59c38d5093b4", ProductName = "AŞUK MAŞUK", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-AŞUKMAŞUK-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "4534cffd-7ed4-406c-9cee-23179740daba", ProductName = "ÇİFTETELLİ BEYAZ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ÇİFTETELLİ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ÇİFTETELLİBEYAZ-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "bac28c61-4b74-4193-a109-f4456c44cf67", ProductName = "LİRİK", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-LİRİK-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "815f578a-5fd8-4c79-8446-ff236b6ffafb", ProductName = "ROMAN FUŞYA", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANFUŞYA-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "a4efe1b6-e7fb-4cee-96aa-1125a3888791", ProductName = "ROMAN KIRMIZI", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANKIRMIZI-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "d302b7f9-1306-4a95-85d4-ff189df4b527", ProductName = "ROMAN PEMBE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANPEMBE-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "dc94da97-75b3-48b7-bfb6-d46984b5f106", ProductName = "ROMAN RENKLİ ETEK", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANRENKLİETEK-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "3d704609-8abd-4a0a-80dd-2ee9f38a3608", ProductName = "ROMAN TURUNCU", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANTURUNCU-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "faa28a13-3b08-4a67-834d-621e4dd3d287", ProductName = "ROMAN YEŞİL", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANYEŞİL-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "69920a1e-2cdf-4b1a-a9cc-329b986e4b69", ProductName = "STİLİZE KIRMIZI E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-STİLİZEKIRMIZI-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "8af7be7f-0ff6-40e1-b206-e89d78430393", ProductName = "STİLİZE KIRMIZI K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-STİLİZEKIRMIZI-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "70d3e030-3eb8-4e54-9af9-d70e0ef78c1d", ProductName = "STİLİZE MAVİ E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-STİLİZEMAVİ-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { Id = "eb3e277a-61f3-4f55-b179-d474841a80a3", ProductName = "STİLİZE MAVİ K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-STİLİZEMAVİ-K-YETİŞKİNKİRALIK.jpg" });


            // KİRALIK YETİŞKİN GÖSTERİ ve TÖREN KOSTÜMLERİ   ////BU KISMIN FOTOLARI YETİŞKİN ROND TÖREN KLASÖRÜNDE
            //YETİŞKİN 4. ROND TÖREN
            // Kiralık Yıl Sonu Gösteri Kıyafetleri - Asker Kıyafeti Kiralama-Çanakkale Askeri Kıyafeti
            builder.HasData(new Product() { Id = "4c0b609e-a2cc-4477-b8d7-9fec89d49462", ProductName = "ÇANAKKALE ASKERİ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-ÇANAKKALEASKERİ-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { Id = "364cd9de-6ddd-47d6-a534-74f3f00a0b7c", ProductName = "FERACE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-FERACE-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { Id = "c8eeda2a-0260-4488-9acf-fddaee71e124", ProductName = "HACİVAT", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-HACİVAT-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { Id = "7203c646-e705-48d1-8141-b2619b227d8d", ProductName = "KARAGÖZ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-KARAGÖZ-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { Id = "0a1ff474-48a1-4366-a120-8ece6ce5ba04", ProductName = "MANASTIR", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-MANASTIR-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { Id = "5fbb3a8c-ea2a-46e7-924a-1c9d40ee6c69", ProductName = "MEHTER", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-MEHTER-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { Id = "cd21938d-8cdf-4c18-a25a-73a2970c2deb", ProductName = "NOEL ANNE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-NOELANNE-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { Id = "8ad91c05-ccae-4482-9f43-f8f197dccdf9", ProductName = "NOEL BABA", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-NOELBABA-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { Id = "6f001fcf-f1b6-4abb-8d91-7038044fabfa", ProductName = "PADİŞAH", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-PADİŞAH-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { Id = "79876823-dd75-471e-b2b5-80650a4bdd47", ProductName = "SEMAZEN", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-SEMAZEN-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { Id = "38c1edea-3339-4f95-8d4a-5f5583660d9f", ProductName = "YENİÇERİ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-YENİÇERİ-YETİŞKİN-KİRALIK.jpg" });

            //**********SATILIK***********
            //HALK OYUNLARI
            //AKDENİZ,EGE,DOĞU ANADOLU,GÜNEY DOĞU,İÇ ANADOLU,KAFKAS,KARADENİZ,MARMARA,TRAKYA
            //TASARIM
            //builder.HasData(new Product() { Id="",ProductName = "ADIYAMAN", IsAdult = false, Size = 8, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "ADIYAMAN", CreatedAt = DateTime.Now });



            //AKDENİZ
            //builder.HasData(new Product() { Id="",ProductName = "AŞUK",  IsAdult = true, Size = 14, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-YENİÇERİ-YETİŞKİN-KİRALIK.jpg" }); GÖRSEL YOK
            builder.HasData(new Product() { Id = "db5aeda4-2830-4ddd-a7ca-02363d58bf25", ProductName = "AŞUK MAŞUK", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AŞUKMAŞUK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "fc72a988-3078-4c69-a8ca-c0f1dc1ec996", ProductName = "ANAMUR E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ANAMUR-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "932c7c4b-36c5-4580-a276-a176a72fd72d", ProductName = "ANAMUR K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ANAMUR-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "0418ebf4-0b73-4042-a5e4-ce396d5b512b", ProductName = "BURDUR E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURDUR-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "f6edd915-a9e4-4713-8e0a-6f1d7efde18f", ProductName = "BURDUR K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURDUR-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "75ce2f59-fa25-4745-bb37-371fc11ab655", ProductName = "BURDUR K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURDUR-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "c5381f46-f707-4fcb-8f1e-605cee507946", ProductName = "MUT E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MUT-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "d3c6ff78-122d-4bee-8880-1afc6fdcb0bc", ProductName = "MUT K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MUT-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "2aec24aa-3fd9-4bbf-9d1f-f614d8574a3d", ProductName = "SİLİFKE E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "299be826-3901-425f-90eb-e445e73ac37c", ProductName = "SİLİFKE E2", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-E2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "a39041d7-3a20-4e73-9334-3fc6d8327e06", ProductName = "SİLİFKE K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "91cb02d4-02ee-4632-a12b-7aaa4b220344", ProductName = "SİLİFKE K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "04c2c202-afa7-4e2c-941c-29f956783f6d", ProductName = "SİLİFKE K3", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-K3-YETİŞKİN-SATILIK.jpg" });
            //builder.HasData(new Product() { Id="",ProductName = "MAŞUK",  IsAdult = true, Size = 14, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-YENİÇERİ-YETİŞKİN-KİRALIK.jpg" });GÖRSEL YOK


            //EGE

            builder.HasData(new Product() { Id = "7ac3fbad-b279-4d80-a8d7-ff1407a6465f", ProductName = "AFYON K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AFYON-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "43c746aa-0830-449b-a594-621f04923cf6", ProductName = "AYDIN E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AYDIN-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "6883361b-7a86-49b9-8fc2-90029770fe22", ProductName = "AYDIN K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AYDIN-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "777bd2e2-cd9e-4d51-b191-c81eb9d113cc", ProductName = "ÇANAKKALE E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÇANAKKALE-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "5787a57d-27d4-4dd2-b5e1-35e4125a6e94", ProductName = "ÇANAKKALE K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÇANAKKALE-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "674202c6-8a9b-4c1f-9eae-0ab056cef8d6", ProductName = "ÇANAKKALE POMAK", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÇANAKKALEPOMAK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "9017f445-e420-4568-b8d9-0d84b3c46aad", ProductName = "DENİZLİ E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DENİZLİ-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "16b681bd-b39a-4891-ab7a-9073365bc1e7", ProductName = "DENİZLİ K", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DENİZLİ-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "4e99c977-d86c-48a7-8bd8-9e71d999539a", ProductName = "İZMİR AÇIK", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-İZMİRAÇIK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "541a5387-302a-478d-99f2-c98f6d979aaa", ProductName = "İZMİR FUŞYA", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-İZMİRFUŞYA-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "b1dae3fe-91d2-42cc-8ba7-dcf237882eac", ProductName = "İZMİR KOYU", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-İZMİRKOYU-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "ef08937f-96ed-443c-80ac-1f7b764d10a1", ProductName = "İZMİR KOYU 2", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-İZMİRKOYU2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "92a51416-05b5-47ef-834f-ad0baccbb932", ProductName = "İZMİR MÜRDÜM", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-İZMİRMÜRDÜM-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "142730b0-0df7-430d-ab80-e750ffe0a6ba", ProductName = "İZMİR MOR", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-İZMİRMOR-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "3a4e5dbe-c93a-4de1-bf6d-fb249bda0f42", ProductName = "MUĞLA K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MUĞLA-K-YETİŞKİN-SATILIK.jpg" });



            //DOGU ANADOLU
            builder.HasData(new Product() { Id = "eec8a34e-e0ea-4a80-bd38-c7db22f84173", ProductName = "AĞRI BEYAZ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AĞRIBEYAZ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "9377deeb-6354-4346-8d56-03b29c97d5fc", ProductName = "AĞRI E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AĞRI-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "bb7ab51d-9d3b-4b32-9e16-6925b504ea1a", ProductName = "AĞRI KADİFE", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AĞRIKADİFE-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "a907697f-9b47-4302-87f3-c4bed83b24c9", ProductName = "ARDAHAN E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARDAHAN-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "cfaa92f4-78cf-4cfd-8d3f-6ccb396d823d", ProductName = "ARDAHAN K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARDAHAN-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "9f0127f0-a604-46ba-a855-ca6be06fcdb2", ProductName = "BİTLİS E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİS-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "958017ca-725f-4d80-b65e-79560a051a03", ProductName = "BİTLİS K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİS-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "39c8cf49-d75e-4703-8958-ec3bbff87723", ProductName = "BİTLİS MAVİ", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİSMAVİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "39f01cd0-ae41-4070-9eb0-0f2423cc3286", ProductName = "ERZİNCAN", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ERZİNCAN-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "8d290951-033a-4adf-8dd9-f8ca4d9d1f2d", ProductName = "ERZURUM E", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ERZURUM-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "befe44f6-84fb-4dd1-bc13-03b43f4ac2e4", ProductName = "HAKKARİ", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-HAKKARİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "7965d633-4f86-44de-8ea4-fe0c68aa6a83", ProductName = "VAN", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VAN-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "fee54746-70cf-44dd-98df-5c09bb8959a8", ProductName = "VAN BEYAZ", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VANBEYAZ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "6bbf3bb3-5dc3-4a5f-b9b7-03cc8fb02fb9", ProductName = "VAN K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VAN-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "6f055d63-314e-4a36-86eb-ea7e11e820c1", ProductName = "VAN LACİVERT", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VANLACİVERT-YETİŞKİN-SATILIK.jpg" });


            //GÜNEYDOGU anadolu
            builder.HasData(new Product() { Id = "caf33f50-8517-4995-a849-4a70bbe202f6", ProductName = "ADANA", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADANA-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "c6633a62-08d6-4613-8f06-a3fcfd76f974", ProductName = "ADANA ABA", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADANAABA-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "3d6e031d-2fcc-46ce-9eb7-268e95ae1323", ProductName = "ADANA K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADANA-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "3da92c21-3bf0-4de1-a187-459271e16106", ProductName = "ADANA K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADANA-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "6f154805-6e66-45a6-a147-87edf4267def", ProductName = "ADIYAMAN E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADIYAMAN-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "ceaa3043-fb10-4638-b942-85d7b5fc20ed", ProductName = "ADIYAMAN K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADIYAMAN-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "31b3b531-3e47-4ccb-9cc9-8e7aafedb810", ProductName = "DİYARBAKIR E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DİYARBAKIR-E-YETİŞKİN-SATILIK.jpg" }); ;
            builder.HasData(new Product() { Id = "7a7cb657-507c-4325-a047-f9d67b6fbffc", ProductName = "DİYARBAKIR K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DİYARBAKIR-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "5cc37e11-afea-478b-b360-1256896a421b", ProductName = "GAZİANTEP ABA", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEPABA-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "85634f26-c60b-4cc5-8c0f-0fad3182a5f3", ProductName = "GAZİANTEP E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "38af7185-32ce-4cf9-95d2-52c4c4d18bce", ProductName = "GAZİANTEP K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "2838e6e6-1238-418a-988c-0346a2abdbc3", ProductName = "GAZİANTEP K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "074db959-27e0-42a0-98d9-0961864e1a7e", ProductName = "GAZİANTEP K3", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-K3-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "9570f221-d5cb-4963-896f-371af0b32c79", ProductName = "URFA E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-URFA-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "04886a46-180e-42d2-a3e5-86df27efaee2", ProductName = "URFA K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-URFA-K-YETİŞKİN-SATILIK.jpg" });

            //iç anadolu
            builder.HasData(new Product() { Id = "0973a418-280f-416d-8df1-7139e28961d2", ProductName = "ANKARA E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ANKARA-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "ea59937e-0296-4758-95ad-196fce18db72", ProductName = "ESKİŞEHİR K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ESKİŞEHİR-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "4b376f71-ebf0-4762-bbff-e61541afa410", ProductName = "ESKİŞEHİR K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ESKİŞEHİR-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "8cefc01c-282b-4866-a0fa-238ed864481c", ProductName = "ESKİŞEHİR K3", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/" });//SİTEDE FOTO YOK
            builder.HasData(new Product() { Id = "efe2c4a0-7529-4f91-9026-696ea0a1f7b7", ProductName = "ESKİŞEHİR K4", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ESKİŞEHİR-K4-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "81c921f4-7fd6-428a-aefe-648e5e11ed46", ProductName = "SİVAS K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/" });//SİTEDE FOTO YOK
            builder.HasData(new Product() { Id = "5a04a2e5-489b-4671-933a-1db0a971f40e", ProductName = "TOKAT K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TOKAT-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "334d6d7e-422b-4376-ac30-161f98aab66d", ProductName = "TOKAT K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TOKAT-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "db9ccc9b-5149-474b-a0b4-af8a13f01bc2", ProductName = "YOZGAT", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-YOZGAT-YETİŞKİN-SATILIK.jpg" });



            //KAFKAS
            builder.HasData(new Product() { Id = "f102b409-56b3-42b4-b70c-25192033ba8d", ProductName = "ÇERKES K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÇERKES-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "64a56e1a-be01-40b0-bc09-1fcaf2161c10", ProductName = "GÜRCÜ K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GÜRCÜ-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "c37d754a-9f08-4f13-8d26-630d896c9371", ProductName = "KAFKAS E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "827e88a3-8580-436c-9112-02d58ca2d7d0", ProductName = "KAFKAS E2", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-E2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "752bc953-0f26-4a2c-afd2-45c5f0b9aecb", ProductName = "KAFKAS E3", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-E3-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "ef23ec60-f223-44c4-915e-196d6b011b94", ProductName = "KAFKAS E4", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-E4-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "c50585c6-d1df-4eaa-b5bf-317678e7d3bb", ProductName = "KAFKAS K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "b1a72d3a-9977-4ae1-ab59-1f5a4ae39a33", ProductName = "KAFKAS K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "2bc1e669-d825-44a8-a11c-656a8209498a", ProductName = "KAFKAS K3", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-K3-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "8d1f8204-852a-4342-b836-767fb2b71263", ProductName = "KAFKAS K4", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-K4-YETİŞKİN-SATILIK.jpg" });



            //KARADENİZ

            builder.HasData(new Product() { Id = "06c505ec-998c-46c0-9163-0188423113b3", ProductName = "ARTVİN E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "61efcce3-e4ac-4aa6-ae46-1b7976b5da88", ProductName = "ARTVİN E2", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-E2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "46c82189-5271-43ba-97aa-a7b0a7dbf126", ProductName = "ARTVİN K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "cec6be0d-a05d-44bc-a5ed-56b0a4d96af3", ProductName = "ARTVİN K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "c87ce8ae-adb7-4007-8c0e-0090d0926e2e", ProductName = "ARTVİN K3", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K3-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "dc91cbb3-94e1-43fe-bf92-06077cf48d87", ProductName = "ARTVİN K4", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K4-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "e87b5530-1a38-4e6e-b6bc-e16c04b6c3b2", ProductName = "ARTVİN K5", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K5-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "5cb4b0a3-e8a7-4ba6-aa60-c88fc65ad77a", ProductName = "GİRESUN E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GİRESUN-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "1da8a34a-6749-48bf-9df9-fe08cd5c7e3f", ProductName = "GİRESUN K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GİRESUN-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "80f38d33-7c5f-4952-809c-85af1dc69962", ProductName = "TRABZON CEPKEN", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONCEPKEN-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "564ea3f5-665c-45f3-85ee-e4c45d3ba362", ProductName = "TRABZON E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "a2a34d3f-9082-4d98-9637-2bd936e60256", ProductName = "TRABZON K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "0a7149b1-6928-4099-b623-787d0201e213", ProductName = "TRABZON K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "93c17f7a-aedf-4f6d-8429-df9ff308d381", ProductName = "TRABZON K3", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-K3-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "8a84a13e-c0cc-4496-81a8-f4550c5807ed", ProductName = "TRABZON K4", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-K4-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "d6ef34e0-f613-405c-a6d8-e2b8f5dd614b", ProductName = "TRABZON K5", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-K5-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "04871b2a-5533-41da-9959-f664809887c3", ProductName = "TRABZON YELEK", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONYELEK-YETİŞKİN-SATILIK.jpg" });



            //MARMARA
            builder.HasData(new Product() { Id = "9f2f3880-4997-4c0b-88e8-f9a74f8b1564", ProductName = "BİLECİK K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİLECİK-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "924916c0-2ad0-493a-b544-5df45fa43152", ProductName = "BOLU K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BOLU-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "6c4014cc-3cc2-481d-9cd6-b13c45da0908", ProductName = "BURSA E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURSA-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "286d76ad-723d-476b-aa84-c7a6541afe81", ProductName = "BURSA E2", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURSA-E2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "034b18a2-33ad-4020-8d9d-5a98891d0be9", ProductName = "BURSA K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURSA-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "01e005f3-0bbb-4ae2-9136-f3afe1353315", ProductName = "BURSA K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURSA-K2-YETİŞKİN-SATILIK.jpg" });


            //TRAKYA

            builder.HasData(new Product() { Id = "cfb34052-097c-4637-b13e-86a2bc255163", ProductName = "BORDO CEPKEN", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BORDOCEPKEN-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "e7d54d6e-42fe-472b-b696-6642067802b3", ProductName = "BORDO KISA YELEK", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BORDOKISAYELEK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "55f0346e-6b98-4a1d-99f8-463b81f6a627", ProductName = "KIRMIZI RENKLİ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KIRMIZIRENKLİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "5a529282-1b91-46d6-b472-e6386b95cf5d", ProductName = "KORDONE FK", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KORDONEFK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "c5d36e60-0945-4e35-9239-22f30c29025f", ProductName = "LASELİ FK", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-LASELİFK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "39c99f61-efbf-4f5c-b084-eac381d82049", ProductName = "MANASTIR KAFTAN", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MANASTIRKAFTAN-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "731dd6c2-2937-4d4b-8c56-63b5cf581729", ProductName = "MANASTIR YELEK", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MANASTIRYELEK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "e7ef9e6e-ea8b-4d2f-a20a-aa8d090fbd49", ProductName = "MOR MARAŞ İŞİ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MORMARAŞİŞİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "b8cc3bd3-ac03-46c4-820b-f7988f3088f7", ProductName = "TRAKYA MOR RENKLİ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MORRENKLİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "ad0f7b6d-0d38-4cb4-b7c9-e4f2dede5654", ProductName = "TRAKYA MOR SALTA", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MORSALTA-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "8191402a-33f8-4195-bd73-3aa71191981e", ProductName = "TRAKYA MOR MONORAY", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MORMONORAY-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "3396c18a-dcd2-4638-8827-2c7fc10d6996", ProductName = "TRAKYA PEMBE RENKLİ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-PEMBERENKLİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "0bf06e4b-d062-4e01-a985-9b05e3f12fd6", ProductName = "TRAKYA BEJ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYABEJ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "d07b2ec3-59c7-46f8-bc3d-6c8c30e1acc2", ProductName = "TRAKYA ÇAĞLA", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAÇAĞLA-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "43bf1028-ea0f-439a-b940-3b81b1f4d683", ProductName = "TRAKYA KREM", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAKREM-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "beacb4b7-e74c-45d8-b8df-60e1a2a50768", ProductName = "TRAKYA MAVİ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAMAVİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "86513d65-cf7e-49d6-bd16-94286e5d60c1", ProductName = "ÜSKÜP BORDO K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPBORDO-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "c6fcf873-e9c2-43c9-81ec-ba09bd063e13", ProductName = "ÜSKÜP BEYAZ CEPKEN", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPBEYAZCEPKEN-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "74770ec2-4585-4665-8f69-b2f0d4f0fc7f", ProductName = "ÜSKÜP BEYAZ K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPBEYAZ-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "1f4cf9f5-2976-4b5c-9428-122096bf3877", ProductName = "ÜSKÜP KIRMIZI K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPKIRMIZI-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "09a2d110-7772-44cd-af5f-27fb951f0544", ProductName = "ÜSKÜP SİYAH K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPSİYAH-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "2d4dadd2-8e1d-495c-b6ab-c0e4d6b167ea", ProductName = "ÜSKÜP E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜP-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { Id = "0dddae8d-37b4-47e5-9c89-95589a3f787a", ProductName = "TRAKYA RENKLİ SALTA", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-RENKLİSALTA-YETİŞKİN-SATILIK.jpg" });
            // c:de kii
        }
    }
}
