using Mate.Entities.Concrete;
using Mate.Entities.EntityConfig.Abstract;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Mate.Entities.EntityConfig.Concrete
{
    public class ProductConfig : BaseConfig<Product>
    {
        public override void Configure(EntityTypeBuilder<Product> builder)
        {
            base.Configure(builder);

            builder.Property(x => x.ProductName).IsRequired().HasMaxLength(50);
            builder.Property(x => x.Description).HasMaxLength(200);

            builder.Property(x => x.IsAdult).IsRequired();
            //builder.Property(x => x.Amount).IsRequired();

            builder.Property(x => x.UnitPriceForSale).HasMaxLength(100000);
            builder.Property(x => x.UnitPriceForRent).HasMaxLength(100000);
            builder.Property(x => x.IsSale).IsRequired();
            builder.Property(x => x.Gender).HasMaxLength(20);


            builder.HasOne(p => p.ProductCategories).WithMany(p => p.Products).HasForeignKey(p => p.ProductCategoryId).IsRequired();
            builder.HasOne(p => p.ProductRegions).WithMany(p => p.Products).HasForeignKey(p => p.ProductRegionId);
            builder.HasOne(p => p.ProductSubRegions).WithMany(p => p.Products).HasForeignKey(p => p.ProductSubRegionId);

            //UnitPriceForsale = 1500,
            //ÇOCUK
            //1.HALK OYUNLARI ÇOCUK

            builder.HasData(new Product() { ProductName = "ADIYAMAN", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "ADIYAMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNADIYAMANÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ANKARA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", ProductSubRegionId = "ANKARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNANKARAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ARTVİN", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "ARTVİN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNARTVİNÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ARTVİN İŞLİ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "ARTVİN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNARTVİN-İŞLİÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "BİLECİK", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "BİLECİK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBİLECİKÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "BİTLİS E", Gender = false, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBİTLİS-EÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "BİTLİS K", Gender = true, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBİTLİS-KÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "BOLU İŞLİ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "BOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBOLU-İŞLİÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "BOLU SADE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "BOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNBOLU-SADEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "DİYARBAKIR", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "DİYARBAKIR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNDİYARBAKIRÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ELAZIĞ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "ELAZIĞ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNELAZIĞÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GAZİANTEP K", Gender = true, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "GAZİANTEP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNGAZİANTEP-KÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GAZİANTEP E", Gender = false, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "GAZİANTEP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNGAZİANTEP-EÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "HALAY KIRMIZI", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductSubRegionId = "HALAY", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNHALAY-KIRMIZIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "HALAY SİYAH", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductSubRegionId = "HALAY", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNHALAY-SİYAHÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KARADENİZ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNKARADENİZÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KAFKAS KIRMIZI", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNKAFKAS-KIRMIZIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KAFKAS MOR", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNKAFKAS-MORÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "SİLİFKE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "SİLİFKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNSİLİFKEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TEKE E", Gender = false, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "TEKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTEKE-EÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TEKE YEŞİL", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "TEKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTEKE-YEŞİLÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TEKE PEMBE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "TEKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTEKE-PEMBEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTRAKYAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÜSKÜP", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", ProductSubRegionId = "ÜSKÜP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNÜSKÜPÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA PEMBE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTRAKYA-PEMBEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA BEYAZ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNTRAKYA-BEYAZÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "VAN", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "VAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNVANÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ZEYBEK BORDO", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNZEYBEK-BORDOÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ZEYBEK E", Gender = false, IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNZEYBEK-EÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ZEYBEK İŞLİ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNZEYBEK-İŞLİÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ZEYBEK MOR", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUNZEYBEK-MORÇOCUKKİRALIK.jpg" });



            //3. STİLİZE DANS ÇOCUK

            builder.HasData(new Product() { ProductName = "ÇAÇA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEÇAÇAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "FRAK", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEFRAKÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GREASE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEGREASEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "HİNT", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEHİNTÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "İSPANYOL", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEİSPANYOLÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ROMAN FUŞYA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEROMANFUŞYAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ROMAN KIRMIZI", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEROMANKIRMIZIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ROMAN KIR (1)", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEROMANKIR1ÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ROMAN MOR", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEROMANMORÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "SALSA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESALSAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "SALSA E", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESALSAEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "STİLİZE KIRMIZI", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZEKIRMIZIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "STİLİZE MOR", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZEMORÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "STİLİZE PEMBE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZEPEMBEÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "STİLİZE SARI", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZESTİLİZESARIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÇİFTETELLİ PEMBE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZEÇİFTETELLİPEMBEÇOCUKKİRALIK.jpg" });




            //ÇOCUK 4. ROND TÖREN
            // Kiralık Yıl Sonu Gösteri Kıyafetleri - Asker Kıyafeti Kiralama-Çanakkale Askeri Kıyafeti
            //KİRALIK ÇOCUK GÖSTERİ ve TÖREN KOSTÜMLERİ




            builder.HasData(new Product() { ProductName = "ARI", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDARIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ASKER", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDASKERÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÇAÇA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDÇAÇAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÇİÇEK", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDÇİÇEKÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "FARE", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDFAREÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "HACİVAT KARAGÖZ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDHACİVATKARAGÖZÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "İSPANYOL", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDİSPANYOLÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KATİBİM", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDKATİBİMÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KIRMIZI BAŞLIKLI KIZ", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDKIRMIZIBAŞLIKLIKIZÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "MEHTER", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDMEHTERÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "MEZUNİYET", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDMEZUNİYETÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "NASREDDİN HOCA", IsAdult = false, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDNASREDDİNHOCAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "NOEL BABA", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDNOELBABAÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÖRDEK", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDÖRDEKÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "PADİŞAH", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDPADİŞAHÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "PALYAÇO", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDPALYAÇOÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "PAMUK PRENSES", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDPAMUKPRENSESÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "SALSA K", Gender = true, IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDSALSAKÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "SEMAZEN", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDSEMAZENÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ŞİRİNLER", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDŞİRİNLERÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TAVŞAN", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDTAVŞANÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "STİLİZE KIRMIZI", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDSTİLİZEKIRMIZIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "STİLİZE SARI", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDSTİLİZESARIÇOCUKKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "YENİÇERİ", IsAdult = false, UnitPriceForSale = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/RONDYENİÇERİÇOCUKKİRALIK.jpg" });




            ////YETİŞKİN
            ////1.HALK OYUNLARI YETİŞKİN
            ////YETİSKİNYÖRESELKIYAFETLERİ
            builder.HasData(new Product() { ProductName = "ADIYAMAN E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "ADIYAMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADIYAMAN-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ADIYAMAN K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "ADIYAMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADIYAMAN-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ANKARA E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", ProductSubRegionId = "ANKARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ANKARA-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ARTVİN E2", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "ARTVİN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-E2-YETİŞKİNKİRALIK.jpG" });
            builder.HasData(new Product() { ProductName = "ARTVİN K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "ARTVİN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "BİLECİK K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", ProductSubRegionId = "BİLECİK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİLECİK-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "BİTLİS BEYAZ E", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİSBEYAZ-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "BİTLİS K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİS-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "BİTLİS MAVİ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "BİTLİS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİSMAVİ-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "BOLU K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "BOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BOLU-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "BURDUR E2", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "BURDUR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURDUR-E2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "BURDUR K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "BURDUR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURDUR-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "DİYARBAKIR E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "DİYARBAKIR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DİYARBAKIR-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "DİYARBAKIR K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "DİYARBAKIR", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DİYARBAKIR-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GAZİANTEP E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "GAZİANTEP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GAZİANTEP K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "GAZİANTEP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GİRESUN E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "GİRESUN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GİRESUN-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GİRESUN K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "GİRESUN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GİRESUN-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "HAKKARİ K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "HAKKARİ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-HAKKARİ-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KAFKAS E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KAFKAS K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "SİLİFKE E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "SİLİFKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "SİLİFKE K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", ProductSubRegionId = "SİLİFKE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA KIRMIZI KADİFE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAKIRMIZIKADİFE-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA KREM", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAKREM-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA MAVİ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAMAVİ-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA MOR MONORAY", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAMORMONORAY-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA PEMBE K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAPEMBE-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON K İŞLİK", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONİŞLİK-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON MOR İŞLİK", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONMORİŞLİK-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON MOR YELEK", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONMORYELEK-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON PEMBE YELEK", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", ProductSubRegionId = "TRABZON", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONPEMBEYELEK-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÜSKÜP E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", ProductSubRegionId = "ÜSKÜP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜP-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÜSKÜP K BORDO", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", ProductSubRegionId = "ÜSKÜP", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPBORDO-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "VAN BEYAZ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "VAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VANBEYAZ-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "VAN K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", ProductSubRegionId = "VAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VAN-K-YETİŞKİNKİRALIK.jpg" });

            builder.HasData(new Product() { ProductName = "ZEYBEK AÇIK E", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKAÇIK-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ZEYBEK AĞIR E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKAĞIR-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ZEYBEK BORDO", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKBORDO-YETİŞKİNKİRALIK.jpg" });// BURALARDA KAYDIRMA YAPTIMMM!!!!!		
            builder.HasData(new Product() { ProductName = "ZEYBEK EŞKİYA E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKEŞKİYA-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ZEYBEK KOYU E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKKOYU-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ZEYBEK MOR", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKMOR-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ZEYBEK PEMBE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKPEMBE-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ZEYBEK MUĞLA", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", ProductSubRegionId = "ZEYBEK", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ZEYBEKMUĞLA-YETİŞKİNKİRALIK.jpg" });
            //2.BİNDALLI VE KINA YETİŞKİN
            builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN BORDO", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANBORDO-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN KIRMIZI", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANKIRMIZI-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN KIRMIZI-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANKIRMIZI-N2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN KIRMIZI-N3", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANKIRMIZI-N3-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN MOR", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANMOR-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN MÜRDÜM", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANMÜRDÜM-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN PEMBE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANPEMBE-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "GELENEKSEL KAFTAN YEŞİL", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-GELENEKSELKAFTANYEŞİL-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KINA KIYAFETİ BORDO", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİBORDO-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KINA KIYAFETİ GRİ-SİYAH", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİGRİSİYAH-YETİŞKİNKİRALIK.jpg" }); ;
            builder.HasData(new Product() { ProductName = "KINA KIYAFETİ KIRMIZI", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİKIRMIZI-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KINA KIYAFETİ KIRMIZI-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİKIRMIZI-N2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KINA KIYAFETİ LACİVERT", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİLACİVERT-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KINA KIYAFETİ LACİVERT-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİLACİVERT-N2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KINA KIYAFETİ LACİVERT-N3", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİLACİVERT-N3-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KINA KIYAFETİ PEMBE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİPEMBE-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KINA KIYAFETİ PEMBE-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİPEMBE-N2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KINA KIYAFETİ ÜSKÜP-N2", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİÜSKÜP-N2-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KINA KIYAFETİ YEŞİL", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "3kına", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/KINABİNDALLI-KINAKIYAFETİYEŞİL-YETİŞKİNKİRALIK.jpg" });

            //3. STİLİZE DANS
            //Kostüm Kiralama - Stilize Dans,Salsa ve Roman Kostümleri
            //YETİŞKİN STİLİZE DANS ve ROMAN KOSTÜMLERİ
            builder.HasData(new Product() { ProductName = "AŞUK MAŞUK", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-AŞUKMAŞUK-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÇİFTETELLİ BEYAZ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ÇİFTETELLİ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ÇİFTETELLİBEYAZ-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "LİRİK", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-LİRİK-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ROMAN FUŞYA", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANFUŞYA-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ROMAN KIRMIZI", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANKIRMIZI-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ROMAN PEMBE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANPEMBE-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ROMAN RENKLİ ETEK", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANRENKLİETEK-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ROMAN TURUNCU", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANTURUNCU-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "ROMAN YEŞİL", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", ProductSubRegionId = "ROMAN", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-ROMANYEŞİL-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "STİLİZE KIRMIZI E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-STİLİZEKIRMIZI-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "STİLİZE KIRMIZI K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-STİLİZEKIRMIZI-K-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "STİLİZE MAVİ E", Gender = false, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-STİLİZEMAVİ-E-YETİŞKİNKİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "STİLİZE MAVİ K", Gender = true, IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "4dans", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/STİLİZE-STİLİZEMAVİ-K-YETİŞKİNKİRALIK.jpg" });


            // KİRALIK YETİŞKİN GÖSTERİ ve TÖREN KOSTÜMLERİ   ////BU KISMIN FOTOLARI YETİŞKİN ROND TÖREN KLASÖRÜNDE
            //YETİŞKİN 4. ROND TÖREN
            // Kiralık Yıl Sonu Gösteri Kıyafetleri - Asker Kıyafeti Kiralama-Çanakkale Askeri Kıyafeti
            builder.HasData(new Product() { ProductName = "ÇANAKKALE ASKERİ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-ÇANAKKALEASKERİ-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "FERACE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-FERACE-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "HACİVAT", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-HACİVAT-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "KARAGÖZ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-KARAGÖZ-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "MANASTIR", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-MANASTIR-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "MEHTER", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-MEHTER-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "NOEL ANNE", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-NOELANNE-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "NOEL BABA", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-NOELBABA-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "PADİŞAH", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-PADİŞAH-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "SEMAZEN", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-SEMAZEN-YETİŞKİN-KİRALIK.jpg" });
            builder.HasData(new Product() { ProductName = "YENİÇERİ", IsAdult = true, IsSale = false, UnitPriceForRent = 1500, ProductCategoryId = "5rond", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-YENİÇERİ-YETİŞKİN-KİRALIK.jpg" });

            //**********SATILIK***********
            //HALK OYUNLARI
            //AKDENİZ,EGE,DOĞU ANADOLU,GÜNEY DOĞU,İÇ ANADOLU,KAFKAS,KARADENİZ,MARMARA,TRAKYA
            //TASARIM
            //builder.HasData(new Product() { ProductName = "ADIYAMAN", IsAdult = false, Size = 8, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", ProductSubRegionId = "ADIYAMAN", CreatedAt = DateTime.Now });

            //AMOUNTLARI UNUTMA!!!!

            //AKDENİZ
            //builder.HasData(new Product() { ProductName = "AŞUK",  IsAdult = true, Size = 14, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-YENİÇERİ-YETİŞKİN-KİRALIK.jpg" }); GÖRSEL YOK
            builder.HasData(new Product() { ProductName = "AŞUK MAŞUK", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AŞUKMAŞUK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ANAMUR E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ANAMUR-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ANAMUR K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ANAMUR-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "BURDUR E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURDUR-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "BURDUR K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURDUR-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "BURDUR K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURDUR-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "MUT E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MUT-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "MUT K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MUT-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "SİLİFKE E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "SİLİFKE E2", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-E2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "SİLİFKE K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "SİLİFKE K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "SİLİFKE K3", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "AKDENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-SİLİFKE-K3-YETİŞKİN-SATILIK.jpg" });
            //builder.HasData(new Product() { ProductName = "MAŞUK",  IsAdult = true, Size = 14, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/ROND-YENİÇERİ-YETİŞKİN-KİRALIK.jpg" });GÖRSEL YOK


            //EGE

            builder.HasData(new Product() { ProductName = "AFYON K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AFYON-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "AYDIN E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AYDIN-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "AYDIN K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AYDIN-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÇANAKKALE E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÇANAKKALE-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÇANAKKALE K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÇANAKKALE-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÇANAKKALE POMAK", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÇANAKKALEPOMAK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "DENİZLİ E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DENİZLİ-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "DENİZLİ K", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DENİZLİ-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "İZMİR AÇIK", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-İZMİRAÇIK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "İZMİR FUŞYA", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-İZMİRFUŞYA-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "İZMİR KOYU", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-İZMİRKOYU-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "İZMİR KOYU 2", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-İZMİRKOYU2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "İZMİR MÜRDÜM", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-İZMİRMÜRDÜM-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "İZMİR MOR", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-İZMİRMOR-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "MUĞLA K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "EGE", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MUĞLA-K-YETİŞKİN-SATILIK.jpg" });



            //DOGU ANADOLU
            builder.HasData(new Product() { ProductName = "AĞRI BEYAZ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AĞRIBEYAZ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "AĞRI E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AĞRI-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "AĞRI KADİFE", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-AĞRIKADİFE-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ARDAHAN E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARDAHAN-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ARDAHAN K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARDAHAN-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "BİTLİS E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİS-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "BİTLİS K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİS-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "BİTLİS MAVİ", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİTLİSMAVİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ERZİNCAN", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ERZİNCAN-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ERZURUM E", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ERZURUM-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "HAKKARİ", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-HAKKARİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "VAN", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VAN-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "VAN BEYAZ", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VANBEYAZ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "VAN K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VAN-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "VAN LACİVERT", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "DOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-VANLACİVERT-YETİŞKİN-SATILIK.jpg" });


            //GÜNEYDOGU anadolu
            builder.HasData(new Product() { ProductName = "ADANA", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADANA-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ADANA ABA", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADANAABA-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ADANA K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADANA-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ADANA K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADANA-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ADIYAMAN E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADIYAMAN-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ADIYAMAN K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ADIYAMAN-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "DİYARBAKIR E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DİYARBAKIR-E-YETİŞKİN-SATILIK.jpg" }); ;
            builder.HasData(new Product() { ProductName = "DİYARBAKIR K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-DİYARBAKIR-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "GAZİANTEP ABA", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEPABA-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "GAZİANTEP E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "GAZİANTEP K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "GAZİANTEP K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "GAZİANTEP K3", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GAZİANTEP-K3-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "URFA E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-URFA-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "URFA K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "GÜNEYDOGU ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-URFA-K-YETİŞKİN-SATILIK.jpg" });

            //iç anadolu
            builder.HasData(new Product() { ProductName = "ANKARA E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ANKARA-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ESKİŞEHİR K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ESKİŞEHİR-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ESKİŞEHİR K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ESKİŞEHİR-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ESKİŞEHİR K3", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/" });//SİTEDE FOTO YOK
            builder.HasData(new Product() { ProductName = "ESKİŞEHİR K4", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ESKİŞEHİR-K4-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "SİVAS K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/" });//SİTEDE FOTO YOK
            builder.HasData(new Product() { ProductName = "TOKAT K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TOKAT-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TOKAT K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TOKAT-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "YOZGAT", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "İÇ ANADOLU", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-YOZGAT-YETİŞKİN-SATILIK.jpg" });



            //KAFKAS
            builder.HasData(new Product() { ProductName = "ÇERKES K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÇERKES-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "GÜRCÜ K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GÜRCÜ-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "KAFKAS E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "KAFKAS E2", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-E2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "KAFKAS E3", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-E3-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "KAFKAS E4", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-E4-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "KAFKAS K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "KAFKAS K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "KAFKAS K3", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-K3-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "KAFKAS K4", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KAFKAS", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KAFKAS-K4-YETİŞKİN-SATILIK.jpg" });



            //KARADENİZ

            builder.HasData(new Product() { ProductName = "ARTVİN E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ARTVİN E2", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-E2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ARTVİN K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ARTVİN K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ARTVİN K3", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K3-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ARTVİN K4", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K4-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ARTVİN K5", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ARTVİN-K5-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "GİRESUN E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GİRESUN-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "GİRESUN K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-GİRESUN-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON CEPKEN", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONCEPKEN-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-K2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON K3", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-K3-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON K4", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-K4-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON K5", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZON-K5-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRABZON YELEK", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "KARADENİZ", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRABZONYELEK-YETİŞKİN-SATILIK.jpg" });



            //MARMARA
            builder.HasData(new Product() { ProductName = "BİLECİK K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BİLECİK-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "BOLU K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BOLU-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "BURSA E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURSA-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "BURSA E2", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURSA-E2-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "BURSA K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURSA-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "BURSA K2", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "MARMARA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BURSA-K2-YETİŞKİN-SATILIK.jpg" });


            //TRAKYA

            builder.HasData(new Product() { ProductName = "TRAKYA BORDO CEPKEN", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BORDOCEPKEN-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA BORDO KISA YELEK", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-BORDOKISAYELEK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA KIRMIZI RENKLİ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KIRMIZIRENKLİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA KORDONE FK", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-KORDONEFK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA LASELİ FK", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-LASELİFK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "MANASTIR KAFTAN", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MANASTIRKAFTAN-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "MANASTIR YELEK", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MANASTIRYELEK-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "MOR MARAŞ İŞİ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MORMARAŞİŞİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA MOR RENKLİ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MORRENKLİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA MOR SALTA", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MORSALTA-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA MOR MONORAY", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-MORMONORAY-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA PEMBE RENKLİ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-PEMBERENKLİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA BEJ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYABEJ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA ÇAĞLA", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAÇAĞLA-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA KREM", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAKREM-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA MAVİ", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-TRAKYAMAVİ-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÜSKÜP BORDO K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPBORDO-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÜSKÜP BEYAZ CEPKEN", IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPBEYAZCEPKEN-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÜSKÜP BEYAZ K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPBEYAZ-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÜSKÜP KIRMIZI K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPKIRMIZI-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÜSKÜP SİYAH K", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜPSİYAH-K-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "ÜSKÜP E", Gender = false, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-ÜSKÜP-E-YETİŞKİN-SATILIK.jpg" });
            builder.HasData(new Product() { ProductName = "TRAKYA RENKLİ SALTA", Gender = true, IsAdult = true, IsSale = true, UnitPriceForSale = 1500, ProductCategoryId = "2halkoyun", ProductRegionId = "TRAKYA", CreatedAt = DateTime.Now, PhotoPath = "/databaseimg/HALKOYUN-RENKLİSALTA-YETİŞKİN-SATILIK.jpg" });
            // c:de kii
        }
    }
}
